/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#eceef0",
        "surface-bright": "#f7f9fb",
        "inverse-primary": "#aec7f7",
        "on-surface": "#191c1e",
        "surface": "#f7f9fb",
        "tertiary-fixed": "#ffddb9",
        "on-tertiary-fixed-variant": "#623f0f",
        "surface-dim": "#d8dadc",
        "surface-container-high": "#e6e8ea",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#465f88",
        "on-tertiary": "#ffffff",
        "outline": "#74777f",
        "outline-variant": "#c4c6cf",
        "secondary-fixed": "#d3e4fe",
        "on-secondary-fixed": "#0b1c30",
        "on-primary-fixed": "#001b3d",
        "secondary-container": "#d0e1fb",
        "surface-variant": "#e0e3e5",
        "primary-fixed-dim": "#aec7f7",
        "primary": "#002046",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#b7c8e1",
        "on-secondary": "#ffffff",
        "primary-container": "#1b365d",
        "on-secondary-fixed-variant": "#38485d",
        "on-primary-fixed-variant": "#2e476f",
        "tertiary-container": "#4f2f00",
        "inverse-on-surface": "#eff1f3",
        "on-background": "#191c1e",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "background": "#f7f9fb",
        "on-tertiary-fixed": "#2b1700",
        "inverse-surface": "#2d3133",
        "surface-container-low": "#f2f4f6",
        "tertiary": "#321c00",
        "on-error": "#ffffff",
        "on-primary-container": "#87a0cd",
        "on-secondary-container": "#54647a",
        "secondary": "#505f76",
        "on-surface-variant": "#44474e"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      }
    },
  },
  plugins: [],
};
