/**
 * Centralized Client Role-Based Access Control (RBAC) definitions
 * Roles: TRADER, AUTHORITY, VERIFIER, GATC, PLATFORM_ADMIN
 */

export const ROLES = {
  TRADER: 'TRADER',
  AUTHORITY: 'AUTHORITY',
  VERIFIER: 'VERIFIER',
  GATC: 'GATC',
  PLATFORM_ADMIN: 'PLATFORM_ADMIN'
};

export const PERMISSIONS = {
  CREATE_INSTRUMENT: [ROLES.TRADER],
  SUBMIT_APPLICATION: [ROLES.TRADER],
  VIEW_OWN_APPLICATIONS: [ROLES.TRADER],
  RECORD_PAYMENT: [ROLES.TRADER],
  RESUBMIT_APPLICATION: [ROLES.TRADER],

  REVIEW_APPLICATION: [ROLES.AUTHORITY],
  RETURN_APPLICATION: [ROLES.AUTHORITY],
  REJECT_APPLICATION: [ROLES.AUTHORITY],
  ASSIGN_VERIFIER: [ROLES.AUTHORITY],
  VERIFY_PAYMENT: [ROLES.AUTHORITY],
  APPROVE_APPLICATION: [ROLES.AUTHORITY],
  GENERATE_CERTIFICATE: [ROLES.AUTHORITY],
  VIEW_OPERATIONS_QUEUE: [ROLES.AUTHORITY],

  VIEW_FIELD_CASES: [ROLES.VERIFIER],
  RECORD_FIELD_VERIFICATION: [ROLES.VERIFIER],
  VIEW_GATC_CASES: [ROLES.GATC],
  RECORD_GATC_TESTING: [ROLES.GATC],
  OPEN_VERIFICATION_WORKSPACE: [ROLES.VERIFIER, ROLES.GATC],

  MANAGE_USERS: [ROLES.PLATFORM_ADMIN],
  MANAGE_ROLES: [ROLES.PLATFORM_ADMIN],
  MANAGE_OFFICES_LABS: [ROLES.PLATFORM_ADMIN],
  MANAGE_MASTER_DATA: [ROLES.PLATFORM_ADMIN],
  VIEW_SYSTEM_HEALTH: [ROLES.PLATFORM_ADMIN],

  VIEW_AUDIT_LOGS: [ROLES.AUTHORITY, ROLES.PLATFORM_ADMIN]
};

export function can(role, permissionKey) {
  const allowed = PERMISSIONS[permissionKey];
  return allowed ? allowed.includes(role) : false;
}
