/**
 * Centralized Client Role-Based Access Control (RBAC) definitions
 * Roles: TRADER, AUTHORITY, VERIFIER, GATC, PLATFORM_ADMIN
 */

export const ROLES = {
  TRADER: 'TRADER',
  AUTHORITY: 'AUTHORITY',
  VERIFIER: 'VERIFIER',
  GATC: 'GATC',
  PLATFORM_ADMIN: 'PLATFORM_ADMIN'
};

export const PERMISSIONS = {
  CREATE_INSTRUMENT: [ROLES.TRADER, ROLES.PLATFORM_ADMIN],
  SUBMIT_APPLICATION: [ROLES.TRADER],
  REVIEW_APPLICATION: [ROLES.AUTHORITY, ROLES.PLATFORM_ADMIN],
  ASSIGN_VERIFIER: [ROLES.AUTHORITY, ROLES.PLATFORM_ADMIN],
  OPEN_VERIFICATION_WORKSPACE: [ROLES.VERIFIER, ROLES.GATC],
  VIEW_AUDIT_LOGS: [ROLES.AUTHORITY, ROLES.PLATFORM_ADMIN]
};

export function can(role, permissionKey) {
  const allowed = PERMISSIONS[permissionKey];
  return allowed ? allowed.includes(role) : false;
}
